#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
