#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo uft allow 'Nginx HTTP'
echo 'Hello World' | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart