#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https:// https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# echo "server {
#     listen 80 default_server;
#     listen[::]:80 default_server;
#     root /var/www/html;
#     index index.html;
#     location /redirect_me {
#     	      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
#     }
# }" > default
# sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
