#!/usr/bin/env bash
# A script that configures a brand new Ubuntu machine

apt-get -y update
apt-get -y install nginx
# create index.html with "Hello World"
echo "Hello World!" > /var/www/html/index.html
# customize 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html
# listen on port 80 and configure redirect_me and 404 html page
# name of the custom HTTP header must be X-Served-By with the value of the host name
echo "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     add_header X-Served-By $HOSTNAME;
     root /var/www/html;
     index index.html;
     location /redirect_me {
     	      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	      }
     error_page 404 /404.html;
     location /404 {
     	      root /var/www/html;
	      internal;
	      }
}" > /etc/nginx/sites-enabled/default
service nginx restart
