#!/usr/bin/env bash
# Bash script that configures a server
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-available/default
sudo rm -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart