#!/usr/bin/env bash
# display To infinity and beyond
# I am invincible!!! when reciving a SIGTERM signal

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
