#!/usr/bin/env bash
# display content of a file /etc/passwd
# display only username, userid, home directory path for the user

while read -r passwd;
do
    echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
