#!/usr/bin/env bash
# diplays bad luck on the 4th loop
# good luck on the 8th loop
# Best School for the rest till 10th

i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
	echo "bad luck"
    elif [ $i == 8 ]
    then
	echo "good luck"
    else
    echo "Best School"
    fi
    (( i++ ))
done
