#!/usr/bin/env bash
# diplays numbers from 1 t0 20
# bad luck from China on the 4th loop
# bad luck from Japan on the 9th loop
# bad luck from Italy on the 17th loop

i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    (( i++ ))
done
