#!/usr/bin/env bash
# configures an Ubuntu server
# localhost resolve to 127.0.0.2
# facebook.com resolve to 8.8.8.8

cp /etc/host ~/hosts.new
sed -i '$/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts