#!/usr/bin/env bash
# Bash script that configures the container
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

# Change user in config file to nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Update the default server to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Change permission of Nginx config file to owner rw, go r
chmod 644 /etc/nginx/nginx.conf
# Kill any running apache process
pkill apache2
sudo -u nginx service nginx restart
