#!/usr/bin/env bash
# Make task #1 short and sweet
sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default
sed -i "s/#usr www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
killall apache2
su nginx -c "service nginx restart"
